name: Unit Tests on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ master ]

permissions:
  pull-requests: write
  checks: write
  statuses: write

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --configuration Release --no-restore --verbosity normal
